apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: channel-peerorg-allchannel
  namespace: peerorg-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: channel-peerorg-allchannel
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: peerorg-net
      network:
        version 1.4.8
      images:
        fabrictools: hyperledger/fabric-tools:1.4.8
        alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.peerorg-net:7051
      localmspid: peerorgMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.icnmicrogrid.net:8080
      authpath: devpeerorg-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/peerorg-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/peerorg-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.fabric.icnmicrogrid.net:8443
    channeltx: |-
      CsoCChgKFggCGgYIraDGmgYiCmFsbGNoYW5uZWwSrQIKqgIKCmFsbGNoYW5uZWwSMRIfCgtBcHBs
      aWNhdGlvbhIQEg4KCnBlZXJvcmdNU1ASABoOCgpDb25zb3J0aXVtEgAa6AESvgEKC0FwcGxpY2F0
      aW9uEq4BCAESDgoKcGVlcm9yZ01TUBIAGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAa
      BkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcS
      DQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlu
      cyoGQWRtaW5zGiUKCkNvbnNvcnRpdW0SFxIVChNNaWNyb2dyaWRDb25zb3J0aXVt