apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: peerorg-net-ca-tools
  namespace: peerorg-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: peerorg-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/catools
  values:
    metadata:
      namespace: peerorg-net
      name: ca-tools
      component_type: peer
      org_name: peerorg
      proxy: haproxy
    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      
    storage:
      storageclassname: peerorgsc
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://vault.icnmicrogrid.net:8080
      authpath: devpeerorg-net-auth
      secretmsp: secretsv2/data/crypto/peerOrganizations/peerorg-net/users/admin/msp
      secrettls: secretsv2/data/crypto/peerOrganizations/peerorg-net/users/admin/tls
      secretorderer: secretsv2/data/crypto/peerOrganizations/peerorg-net/orderers
      secretpeer: secretsv2/data/crypto/peerOrganizations/peerorg-net/peers
      secretpeerorderertls: secretsv2/data/crypto/peerOrganizations/peerorg-net/orderer/tls
      secretambassador: secretsv2/data/crypto/peerOrganizations/peerorg-net/ambassador
      secretcert: secretsv2/data/crypto/peerOrganizations/peerorg-net/ca?ca.peerorg-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/peerorg-net/ca?peerorg-net-CA.key
      secretcouchdb: secretsv2/data/credentials/peerorg-net/couchdb/peerorg
      secretconfigfile: secretsv2/data/crypto/peerOrganizations/peerorg-net/msp/config
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: fabric.icnmicrogrid.net
      component_subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      cert_subject: O=Manufacturer/OU=Manufacturer/L=47.38,8.54,Zurich/C=CH
      component_country: CH
      component_state: Zurich
      component_location: Zurich
      ca_url: ca.peerorg-net.fabric.icnmicrogrid.net:8443

    orderers:
      name: orderer1-
    orderers_info:
      - name: orderer1
        path: "certs/orderer1-ca.crt"

    peers:
      name: peer0,-      
    peer_count: "1"
    checks:
      refresh_cert_value: False
      add_peer_value: False
